### ISSUE TITLE
rollup 3.x support

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [swiing/rollup-plugin-import-assertions#5]
Current version is not compliant with latest rollup

**Comment by swiing** [comment]
Could you elaborate what error you get?

**Comment by tzvetelin-vassilev** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: data-manager@1.0.0
npm ERR! Found: rollup@3.20.2
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^3.19.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^2.60.0" from rollup-plugin-import-assertions@0.4.0
npm ERR! node_modules/rollup-plugin-import-assertions
npm ERR!   rollup-plugin-import-assertions@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by tzvetelin-vassilev** [comment]
Thanks, when this update will be accessible in npm registry?

**Comment by swiing** [comment]
It is undecided at this stage. Meanwhile you can use the following dependency
`"github:swiing/rollup-plugin-import-assertions"`

**Comment by swiing** [comment]
It looks like rollup 3.x has introduced [some support of import assertions](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#300). Although from my very quick scan:

- it does not seem to handle well `type: 'css'` (see [here](https://github.com/rollup/rollup/issues/4818))
- support for `type: 'json'` is qualified as [basic](https://github.com/rollup/rollup/pull/4646)

I'd rather have a deeper look and check _if_ (and in which cases) it would make sense to leverage rollup-v3 native code.

Hence, I re-open this issue.

**Comment by swiing** [comment]
> It looks like rollup 3.x has introduced [some support of import assertions](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#300). 
> I'd rather have a deeper look and check _if_ (and in which cases) it would make sense to leverage rollup-v3 native code.
> 
> Hence, I re-open this issue.

Addressed by https://github.com/swiing/rollup-plugin-import-assertions/commit/d38f7241e621d62dbb7dc1d1315d9ac2da2332ba.
Closing...

**Comment by swiing** [comment]
> Thanks, when this update will be accessible in npm registry?

done
